onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {Top-Level Ports}
add wave -noupdate /sequencer_qsys_tb/qsys_0/clk_50m_clk
add wave -noupdate /sequencer_qsys_tb/qsys_0/pmbus_scl
add wave -noupdate /sequencer_qsys_tb/qsys_0/pmbus_sda
add wave -noupdate /sequencer_qsys_tb/qsys_0/pb_resetn_reset_n
add wave -noupdate /sequencer_qsys_tb/qsys_0/por_pulse_resetn_reset
add wave -noupdate /sequencer_qsys_tb/qsys_0/reset_sequencer_reset_out0_reset
add wave -noupdate /sequencer_qsys_tb/qsys_0/reset_sequencer_reset_out1_reset
add wave -noupdate /sequencer_qsys_tb/qsys_0/pg_power_good
add wave -noupdate /sequencer_qsys_tb/qsys_0/seqctl_vrail_dchg
add wave -noupdate /sequencer_qsys_tb/qsys_0/seqctl_vrail_ena
add wave -noupdate /sequencer_qsys_tb/qsys_0/seqstat_nfault
add wave -noupdate /sequencer_qsys_tb/qsys_0/smb_alertn_smb_alertn
add wave -noupdate -divider {Sequencer Signals}
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/seq_enable
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/seq_keepalive
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/vrail_fault
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/fault_pwrgd
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/fault_pwrgd_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/next_oe
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/vrail_ena_i
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/vrail_dchg_i
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/group_pwrgd
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/nFault_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/cntr_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/cntr_en
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/cntr_rtry_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/cntr_rstrtdly_en
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/seq_restart_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_core/poks_low
add wave -noupdate {/sequencer_qsys_tb/qsys_0/sequencer_core/G_SEQCTRL[0]/U_SEQCTRL/seq_state_q}
add wave -noupdate {/sequencer_qsys_tb/qsys_0/sequencer_core/G_SEQCTRL[1]/U_SEQCTRL/seq_state_q}
add wave -noupdate {/sequencer_qsys_tb/qsys_0/sequencer_core/G_SEQCTRL[2]/U_SEQCTRL/seq_state_q}
add wave -noupdate {/sequencer_qsys_tb/qsys_0/sequencer_core/G_SEQCTRL[3]/U_SEQCTRL/seq_state_q}
add wave -noupdate {/sequencer_qsys_tb/qsys_0/sequencer_core/G_SEQCTRL[4]/U_SEQCTRL/seq_state_q}
add wave -noupdate {/sequencer_qsys_tb/qsys_0/sequencer_core/G_SEQCTRL[5]/U_SEQCTRL/seq_state_q}
add wave -noupdate -divider {Voltage Monitor Signals}
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/ADC_VIN_LEVEL_Q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/adc_vout_level_ary_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/alarm_vin_ov_fault_limit_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/alarm_vin_ov_warn_limit_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/alarm_vin_uv_warn_limit_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/alarm_vin_uv_fault_limit_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/reg_vin_ov_fault_limit_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/reg_vin_ov_warn_limit_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/reg_vin_uv_warn_limit_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/reg_vin_uv_fault_limit_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/reg_status_word_err
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/reg_status_vout_err
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/reg_status_input_q
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/reg_status_cml_err
add wave -noupdate /sequencer_qsys_tb/qsys_0/sequencer_monitor/u_vm_regs/reg_status_other_err
