# TCL File Generated by Component Editor 18.0
# Thu Nov 29 22:17:24 CST 2018
# DO NOT MODIFY


# 
# avmm_sequencer "Avalon-MM Sequencer" v1.0
#  2018.11.29.22:17:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avmm_sequencer
# 
set_module_property DESCRIPTION ""
set_module_property NAME avmm_sequencer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon-MM Sequencer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avmm_sequencer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_sequencer_pkg.sv SYSTEM_VERILOG PATH avmm_sequencer_pkg.sv
add_fileset_file avmm_sequencer.sv SYSTEM_VERILOG PATH avmm_sequencer.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avmm_sequencer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_sequencer_pkg.sv SYSTEM_VERILOG PATH avmm_sequencer_pkg.sv
add_fileset_file avmm_sequencer.sv SYSTEM_VERILOG PATH avmm_sequencer.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avmm_sequencer
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_sequencer_pkg.sv SYSTEM_VERILOG PATH avmm_sequencer_pkg.sv
add_fileset_file avmm_sequencer.sv SYSTEM_VERILOG PATH avmm_sequencer.sv


# 
# parameters
# 
add_parameter P_ADDRSIZE INTEGER 8
set_parameter_property P_ADDRSIZE DEFAULT_VALUE 8
set_parameter_property P_ADDRSIZE DISPLAY_NAME "Address Width"
set_parameter_property P_ADDRSIZE TYPE INTEGER
set_parameter_property P_ADDRSIZE UNITS bits
set_parameter_property P_ADDRSIZE HDL_PARAMETER true
add_parameter P_DATASIZE INTEGER 32
set_parameter_property P_DATASIZE DEFAULT_VALUE 32
set_parameter_property P_DATASIZE DISPLAY_NAME "Data Width"
set_parameter_property P_DATASIZE TYPE INTEGER
set_parameter_property P_DATASIZE UNITS bits
set_parameter_property P_DATASIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLOCK clk Input 1


# 
# connection point resetn
# 
add_interface resetn reset end
set_interface_property resetn associatedClock clock
set_interface_property resetn synchronousEdges DEASSERT
set_interface_property resetn ENABLED true
set_interface_property resetn EXPORT_OF ""
set_interface_property resetn PORT_NAME_MAP ""
set_interface_property resetn CMSIS_SVD_VARIABLES ""
set_interface_property resetn SVD_ADDRESS_GROUP ""

add_interface_port resetn RESET_N reset_n Input 1


# 
# connection point avm
# 
add_interface avm avalon start
set_interface_property avm addressUnits SYMBOLS
set_interface_property avm associatedClock clock
set_interface_property avm associatedReset resetn
set_interface_property avm bitsPerSymbol 8
set_interface_property avm burstOnBurstBoundariesOnly false
set_interface_property avm burstcountUnits WORDS
set_interface_property avm doStreamReads false
set_interface_property avm doStreamWrites false
set_interface_property avm holdTime 0
set_interface_property avm linewrapBursts false
set_interface_property avm maximumPendingReadTransactions 0
set_interface_property avm maximumPendingWriteTransactions 0
set_interface_property avm readLatency 0
set_interface_property avm readWaitTime 1
set_interface_property avm setupTime 0
set_interface_property avm timingUnits Cycles
set_interface_property avm writeWaitTime 0
set_interface_property avm ENABLED true
set_interface_property avm EXPORT_OF ""
set_interface_property avm PORT_NAME_MAP ""
set_interface_property avm CMSIS_SVD_VARIABLES ""
set_interface_property avm SVD_ADDRESS_GROUP ""

add_interface_port avm AVM_M0_ADDRESS address Output P_ADDRSIZE
add_interface_port avm AVM_M0_READ read Output 1
add_interface_port avm AVM_M0_WAITREQUEST waitrequest Input 1
add_interface_port avm AVM_M0_READDATA readdata Input P_DATASIZE
add_interface_port avm AVM_M0_WRITE write Output 1
add_interface_port avm AVM_M0_WRITEDATA writedata Output P_DATASIZE

