# TCL File Generated by Component Editor 23.1
# Tue Dec 10 17:13:51 CST 2024
# DO NOT MODIFY


# 
# nvram_ctrl_m10_ocflash "MAX10 OCFlash Controller" v1.0
#  2024.12.10.17:13:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module nvram_ctrl_m10_ocflash
# 
set_module_property DESCRIPTION ""
set_module_property NAME nvram_ctrl_m10_ocflash
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "MAX10 OCFlash Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL nvram_ctrl_m10_ocflash
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sequencer_vmon_pkg.sv SYSTEM_VERILOG PATH sequencer_vmon_pkg.sv
add_fileset_file nvram_ctrl_m10_ocflash.sv SYSTEM_VERILOG PATH nvram_ctrl_m10_ocflash.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL nvram_ctrl_m10_ocflash
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file sequencer_vmon_pkg.sv SYSTEM_VERILOG PATH sequencer_vmon_pkg.sv
add_fileset_file nvram_ctrl_m10_ocflash.sv SYSTEM_VERILOG PATH nvram_ctrl_m10_ocflash.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL nvram_ctrl_m10_ocflash
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file sequencer_vmon_pkg.sv SYSTEM_VERILOG PATH sequencer_vmon_pkg.sv
add_fileset_file nvram_ctrl_m10_ocflash.sv SYSTEM_VERILOG PATH nvram_ctrl_m10_ocflash.sv


# 
# parameters
# 
add_parameter VRAILS INTEGER 4
set_parameter_property VRAILS DEFAULT_VALUE 4
set_parameter_property VRAILS DISPLAY_NAME "Output Voltage Rails"
set_parameter_property VRAILS TYPE INTEGER
set_parameter_property VRAILS UNITS None
set_parameter_property VRAILS ALLOWED_RANGES 0:143
set_parameter_property VRAILS DESCRIPTION "The number of output voltage rails being sequenced."
set_parameter_property VRAILS HDL_PARAMETER true
add_parameter P_ADDRSIZE INTEGER 11
set_parameter_property P_ADDRSIZE DEFAULT_VALUE 11
set_parameter_property P_ADDRSIZE DISPLAY_NAME "Flash Address Bus Width"
set_parameter_property P_ADDRSIZE TYPE INTEGER
set_parameter_property P_ADDRSIZE UNITS None
set_parameter_property P_ADDRSIZE ALLOWED_RANGES 1:32
set_parameter_property P_ADDRSIZE DESCRIPTION "The width of the address bus expected by the downstream flash component."
set_parameter_property P_ADDRSIZE HDL_PARAMETER true
add_parameter P_DATASIZE INTEGER 32
set_parameter_property P_DATASIZE DEFAULT_VALUE 32
set_parameter_property P_DATASIZE DISPLAY_NAME "Flash Data Bus Width"
set_parameter_property P_DATASIZE TYPE INTEGER
set_parameter_property P_DATASIZE UNITS None
set_parameter_property P_DATASIZE ALLOWED_RANGES 8:1024
set_parameter_property P_DATASIZE DESCRIPTION "The width of the data bus expected by the downstream flash component (for both control and data interfaces)."
set_parameter_property P_DATASIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLOCK clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RESET_N reset_n Input 1


# 
# connection point nvlog_conduit
# 
add_interface nvlog_conduit conduit end
set_interface_property nvlog_conduit associatedClock ""
set_interface_property nvlog_conduit associatedReset ""
set_interface_property nvlog_conduit ENABLED true
set_interface_property nvlog_conduit EXPORT_OF ""
set_interface_property nvlog_conduit PORT_NAME_MAP ""
set_interface_property nvlog_conduit CMSIS_SVD_VARIABLES ""
set_interface_property nvlog_conduit SVD_ADDRESS_GROUP ""

add_interface_port nvlog_conduit FLASH_ERASEPAGE flash_erasepage Input 1
add_interface_port nvlog_conduit NVLOG_ERROR nvlog_error Input 1
add_interface_port nvlog_conduit NVLOG_BBENA nvlog_bbena Input 1
add_interface_port nvlog_conduit NVLOG_FAULTTYPE nvlog_faulttype Input 8
add_interface_port nvlog_conduit NVLOG_FAULTPAGE nvlog_faultpage Input 8
add_interface_port nvlog_conduit NVLOG_TIMESTAMP nvlog_timestamp Input 32
add_interface_port nvlog_conduit NVLOG_BBDATA nvlog_bbdata Input "(VRAILS*2) + 2"
add_interface_port nvlog_conduit NVLOG_FLASHENTRIES_Q nvlog_flashentries_q Output 8


# 
# connection point flash_data
# 
add_interface flash_data avalon start
set_interface_property flash_data addressUnits SYMBOLS
set_interface_property flash_data associatedClock clock
set_interface_property flash_data associatedReset reset
set_interface_property flash_data bitsPerSymbol 8
set_interface_property flash_data burstOnBurstBoundariesOnly false
set_interface_property flash_data burstcountUnits WORDS
set_interface_property flash_data doStreamReads false
set_interface_property flash_data doStreamWrites false
set_interface_property flash_data holdTime 0
set_interface_property flash_data linewrapBursts false
set_interface_property flash_data maximumPendingReadTransactions 0
set_interface_property flash_data maximumPendingWriteTransactions 0
set_interface_property flash_data readLatency 0
set_interface_property flash_data readWaitTime 1
set_interface_property flash_data setupTime 0
set_interface_property flash_data timingUnits Cycles
set_interface_property flash_data writeWaitTime 0
set_interface_property flash_data ENABLED true
set_interface_property flash_data EXPORT_OF ""
set_interface_property flash_data PORT_NAME_MAP ""
set_interface_property flash_data CMSIS_SVD_VARIABLES ""
set_interface_property flash_data SVD_ADDRESS_GROUP ""

add_interface_port flash_data AVM_DATA_READ read Output 1
add_interface_port flash_data AVM_DATA_WRITE write Output 1
add_interface_port flash_data AVM_DATA_WAITREQUEST waitrequest Input 1
add_interface_port flash_data AVM_DATA_ADDRESS address Output "P_ADDRSIZE"
add_interface_port flash_data AVM_DATA_READDATA readdata Input "P_DATASIZE"
add_interface_port flash_data AVM_DATA_WRITEDATA writedata Output "P_DATASIZE"


# 
# connection point flash_csr
# 
add_interface flash_csr avalon start
set_interface_property flash_csr addressUnits SYMBOLS
set_interface_property flash_csr associatedClock clock
set_interface_property flash_csr associatedReset reset
set_interface_property flash_csr bitsPerSymbol 8
set_interface_property flash_csr burstOnBurstBoundariesOnly false
set_interface_property flash_csr burstcountUnits WORDS
set_interface_property flash_csr doStreamReads false
set_interface_property flash_csr doStreamWrites false
set_interface_property flash_csr holdTime 0
set_interface_property flash_csr linewrapBursts false
set_interface_property flash_csr maximumPendingReadTransactions 0
set_interface_property flash_csr maximumPendingWriteTransactions 0
set_interface_property flash_csr readLatency 0
set_interface_property flash_csr readWaitTime 1
set_interface_property flash_csr setupTime 0
set_interface_property flash_csr timingUnits Cycles
set_interface_property flash_csr writeWaitTime 0
set_interface_property flash_csr ENABLED true
set_interface_property flash_csr EXPORT_OF ""
set_interface_property flash_csr PORT_NAME_MAP ""
set_interface_property flash_csr CMSIS_SVD_VARIABLES ""
set_interface_property flash_csr SVD_ADDRESS_GROUP ""

add_interface_port flash_csr AVM_CSR_READ read Output 1
add_interface_port flash_csr AVM_CSR_WRITE write Output 1
add_interface_port flash_csr AVM_CSR_WAITREQUEST waitrequest Input 1
add_interface_port flash_csr AVM_CSR_ADDRESS address Output 3
add_interface_port flash_csr AVM_CSR_READDATA readdata Input "P_DATASIZE"
add_interface_port flash_csr AVM_CSR_WRITEDATA writedata Output "P_DATASIZE"
