# TCL File Generated by Component Editor 18.0
# Wed Nov 21 09:03:02 CST 2018
# DO NOT MODIFY


# 
# pll_lock_splitter "pll_lock_splitter" v1.0
#  2018.11.21.09:03:02
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pll_lock_splitter
# 
set_module_property DESCRIPTION ""
set_module_property NAME pll_lock_splitter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "PLL Locked Splitter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pll_lock_splitter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pll_lock_splitter.sv SYSTEM_VERILOG PATH pll_lock_splitter.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pll_lock_splitter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pll_lock_splitter.sv SYSTEM_VERILOG PATH pll_lock_splitter.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL pll_lock_splitter
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pll_lock_splitter.sv SYSTEM_VERILOG PATH pll_lock_splitter.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point pll_locked
# 
add_interface pll_locked conduit end
set_interface_property pll_locked associatedClock ""
set_interface_property pll_locked associatedReset ""
set_interface_property pll_locked ENABLED true
set_interface_property pll_locked EXPORT_OF ""
set_interface_property pll_locked PORT_NAME_MAP ""
set_interface_property pll_locked CMSIS_SVD_VARIABLES ""
set_interface_property pll_locked SVD_ADDRESS_GROUP ""

add_interface_port pll_locked PLL_LOCKED export Input 1


# 
# connection point locked_out
# 
add_interface locked1_out conduit end
set_interface_property locked1_out associatedClock ""
set_interface_property locked1_out associatedReset ""
set_interface_property locked1_out ENABLED true
set_interface_property locked1_out EXPORT_OF ""
set_interface_property locked1_out PORT_NAME_MAP ""
set_interface_property locked1_out CMSIS_SVD_VARIABLES ""
set_interface_property locked1_out SVD_ADDRESS_GROUP ""

add_interface_port locked1_out LOCKED1 reset1_dsrt_qual Output 1


# 
# connection point locked_out
# 
add_interface locked2_out conduit end
set_interface_property locked2_out associatedClock ""
set_interface_property locked2_out associatedReset ""
set_interface_property locked2_out ENABLED true
set_interface_property locked2_out EXPORT_OF ""
set_interface_property locked2_out PORT_NAME_MAP ""
set_interface_property locked2_out CMSIS_SVD_VARIABLES ""
set_interface_property locked2_out SVD_ADDRESS_GROUP ""

add_interface_port locked2_out LOCKED2 export Output 1

