# TCL File Generated by Component Editor 18.1
# Fri May 17 16:41:51 CDT 2019
# DO NOT MODIFY


# 
# PMBus_Slave "PMBus Slave to Avalon-MM Master Bridge" v1.0
#  2019.05.17.16:41:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module PMBus_Slave
# 
set_module_property DESCRIPTION ""
set_module_property NAME PMBus_Slave
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "PMBus Slave to Avalon-MM Master Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pmbus_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pmbus_slave.sv SYSTEM_VERILOG PATH pmbus_slave.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pmbus_slave
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pmbus_slave.sv SYSTEM_VERILOG PATH pmbus_slave.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL pmbus_slave
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pmbus_slave.sv SYSTEM_VERILOG PATH pmbus_slave.sv


# 
# parameters
# 
add_parameter PMB_SLAVE_ADDR STD_LOGIC_VECTOR 85 ""
set_parameter_property PMB_SLAVE_ADDR DEFAULT_VALUE 85
set_parameter_property PMB_SLAVE_ADDR DISPLAY_NAME "I2C Slave Address"
set_parameter_property PMB_SLAVE_ADDR DESCRIPTION "Seven-bit destination address for which the slave device should respond."
set_parameter_property PMB_SLAVE_ADDR WIDTH 7
set_parameter_property PMB_SLAVE_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property PMB_SLAVE_ADDR UNITS None
set_parameter_property PMB_SLAVE_ADDR HDL_PARAMETER true

add_parameter MAX_BYTES INTEGER 2
set_parameter_property MAX_BYTES DEFAULT_VALUE 2
set_parameter_property MAX_BYTES DISPLAY_NAME "Databus Width (Bytes)"
set_parameter_property MAX_BYTES DESCRIPTION "Width of the databus.  This should be equal to or greater than the maximum number bytes of data transferred per command, and MUST equal the width of the slave device, or incorrect commands will be transferred."
set_parameter_property MAX_BYTES TYPE INTEGER
set_parameter_property MAX_BYTES ALLOWED_RANGES {1 2 4 8 16 32 64 128}
set_parameter_property MAX_BYTES UNITS None
set_parameter_property MAX_BYTES HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLOCK clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RESET_N reset_n Input 1


# 
# connection point PMBus
# 
add_interface PMBus conduit end
set_interface_property PMBus associatedClock clock
set_interface_property PMBus associatedReset reset
set_interface_property PMBus ENABLED true
set_interface_property PMBus EXPORT_OF ""
set_interface_property PMBus PORT_NAME_MAP ""
set_interface_property PMBus CMSIS_SVD_VARIABLES ""
set_interface_property PMBus SVD_ADDRESS_GROUP ""

add_interface_port PMBus SCL scl Input 1
add_interface_port PMBus SDA sda Bidir 1


# 
# connection point PMBus_sideband
# 
add_interface PMBus_sideband conduit end
set_interface_property PMBus_sideband associatedClock clock
set_interface_property PMBus_sideband associatedReset reset
set_interface_property PMBus_sideband ENABLED true
set_interface_property PMBus_sideband EXPORT_OF ""
set_interface_property PMBus_sideband PORT_NAME_MAP ""
set_interface_property PMBus_sideband CMSIS_SVD_VARIABLES ""
set_interface_property PMBus_sideband SVD_ADDRESS_GROUP ""

add_interface_port PMBus_sideband SMB_STOP smb_stop Output 1


# 
# connection point PMBus_AVS
# 
add_interface PMBus_AVS avalon start
set_interface_property PMBus_AVS addressUnits WORDS
set_interface_property PMBus_AVS associatedClock clock
set_interface_property PMBus_AVS associatedReset reset
set_interface_property PMBus_AVS bitsPerSymbol 8
set_interface_property PMBus_AVS burstOnBurstBoundariesOnly false
set_interface_property PMBus_AVS burstcountUnits WORDS
set_interface_property PMBus_AVS doStreamReads false
set_interface_property PMBus_AVS doStreamWrites false
set_interface_property PMBus_AVS holdTime 0
set_interface_property PMBus_AVS linewrapBursts false
set_interface_property PMBus_AVS maximumPendingReadTransactions 0
set_interface_property PMBus_AVS maximumPendingWriteTransactions 0
set_interface_property PMBus_AVS readLatency 0
set_interface_property PMBus_AVS readWaitTime 1
set_interface_property PMBus_AVS setupTime 0
set_interface_property PMBus_AVS timingUnits Cycles
set_interface_property PMBus_AVS writeWaitTime 0
set_interface_property PMBus_AVS ENABLED true
set_interface_property PMBus_AVS EXPORT_OF ""
set_interface_property PMBus_AVS PORT_NAME_MAP ""
set_interface_property PMBus_AVS CMSIS_SVD_VARIABLES ""
set_interface_property PMBus_AVS SVD_ADDRESS_GROUP ""

add_interface_port PMBus_AVS SMB_COMMAND address Output 8
add_interface_port PMBus_AVS SMB_BYTEEN byteenable Output MAX_BYTES
add_interface_port PMBus_AVS SMB_READ read Output 1
add_interface_port PMBus_AVS SMB_WRITE write Output 1
add_interface_port PMBus_AVS SMB_WAITREQUEST waitrequest Input 1
add_interface_port PMBus_AVS SMB_READDATA readdata Input MAX_BYTES*8
add_interface_port PMBus_AVS SMB_WRITEDATA writedata Output MAX_BYTES*8

