# TCL File Generated by Component Editor 22.1
# Fri Dec 08 17:50:26 CST 2023
# DO NOT MODIFY


# 
# por_pulse "POR Pulse" v1.0
#  2023.12.08.17:50:26
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module por_pulse
# 
set_module_property DESCRIPTION ""
set_module_property NAME por_pulse
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "POR Pulse"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL por_pulse
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file por_pulse.sv SYSTEM_VERILOG PATH por_pulse.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL por_pulse
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file por_pulse.sv SYSTEM_VERILOG PATH por_pulse.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL por_pulse
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file por_pulse.sv SYSTEM_VERILOG PATH por_pulse.sv


# 
# parameters
# 
add_parameter P_WIDTH INTEGER 16 "The desired duration of the power-on reset pulse in clock cycles."
set_parameter_property P_WIDTH DEFAULT_VALUE 16
set_parameter_property P_WIDTH DISPLAY_NAME "POR Pulse Width"
set_parameter_property P_WIDTH TYPE INTEGER
set_parameter_property P_WIDTH UNITS Cycles
set_parameter_property P_WIDTH ALLOWED_RANGES 2:64
set_parameter_property P_WIDTH DESCRIPTION "The desired duration of the power-on reset pulse in clock cycles."
set_parameter_property P_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLOCK clk Input 1


# 
# connection point resetn
# 
add_interface resetn reset start
set_interface_property resetn associatedClock clock
set_interface_property resetn associatedDirectReset ""
set_interface_property resetn associatedResetSinks ""
set_interface_property resetn synchronousEdges DEASSERT
set_interface_property resetn ENABLED true
set_interface_property resetn EXPORT_OF ""
set_interface_property resetn PORT_NAME_MAP ""
set_interface_property resetn CMSIS_SVD_VARIABLES ""
set_interface_property resetn SVD_ADDRESS_GROUP ""

add_interface_port resetn RESET_N reset_n Output 1

